columns_to_select:
  city: STRING
  zone: STRING
  date_time: TIMESTAMP
  updated_at: TIMESTAMP
  created_at: TIMESTAMP
  power_consumption_total: INT
  power_production_total: INT
  power_import_total: INT
  power_export_total: INT
  fossil_free_percentage: INT
  renewable_percentage: INT
  is_estimated: BOOLEAN
  estimation_method: STRING
  temporal_granularity: STRING
  cons_nuclear: INT
  cons_geothermal: INT
  cons_biomass: INT
  cons_coal: INT
  cons_wind: INT
  cons_solar: INT
  cons_hydro: INT
  cons_gas: INT
  cons_oil: INT
  cons_unknown: INT
  cons_hydro_discharge: INT
  cons_battery_discharge: INT
  prod_nuclear: INT
  prod_geothermal: INT
  prod_biomass: INT
  prod_coal: INT
  prod_wind: INT
  prod_solar: INT
  prod_hydro: INT
  prod_gas: INT
  prod_oil: INT
  prod_unknown: INT
  prod_hydro_discharge: INT
  prod_battery_discharge: INT