electricity_use_extract_arg_map:
  extract_zone: zone
electricity_use_clean_arg_map:
  clean_city: city
  clean_input_table: input_table
  clean_output_table: output_table
  clean_write_options: write_options
  clean_write_mode: write_mode