api_fields_extract:
  zone: [zone, "UNKNOWN"]
  date_time: [datetime, "1970-01-01T00:00Z"]
  updated_at: [updatedAt, "1970-01-01T00:00Z"]
  created_at: [createdAt, "1970-01-01T00:00Z"]
  fossil_free_percentage: [fossilFreePercentage, 0]
  renewable_percentage: [renewablePercentage, 0]
  power_consumption_total: [powerConsumptionTotal, 0]
  power_production_total: [powerProductionTotal, 0]
  power_import_total: [powerImportTotal, 0]
  power_export_total: [powerExportTotal, 0]
  is_estimated: [isEstimated, True]
  estimation_method: [estimationMethod, "UNKNOWN"]
  temporal_granularity: [temporalGranularity, "UNKNOWN"]
  cons_nuclear: [powerConsumptionBreakdown, nuclear, 0]
  cons_geothermal: [powerConsumptionBreakdown, geothermal, 0]
  cons_biomass: [powerConsumptionBreakdown, biomass, 0]
  cons_coal: [powerConsumptionBreakdown, coal, 0]
  cons_wind: [powerConsumptionBreakdown, wind, 0]
  cons_solar: [powerConsumptionBreakdown, solar, 0]
  cons_hydro: [powerConsumptionBreakdown, hydro, 0]
  cons_gas: [powerConsumptionBreakdown, gas, 0]
  cons_oil: [powerConsumptionBreakdown, oil, 0]
  cons_unknown: [powerConsumptionBreakdown, unknown, 0]
  cons_hydro_discharge: [powerConsumptionBreakdown, hydro discharge, 0]
  cons_battery_discharge: [powerConsumptionBreakdown, battery discharge, 0]
  prod_nuclear: [powerProductionBreakdown, nuclear, 0]
  prod_geothermal: [powerProductionBreakdown, geothermal, 0]
  prod_biomass: [powerProductionBreakdown, biomass, 0]
  prod_coal: [powerProductionBreakdown, coal, 0]
  prod_wind: [powerProductionBreakdown, wind, 0]
  prod_solar: [powerProductionBreakdown, solar, 0]
  prod_hydro: [powerProductionBreakdown, hydro, 0]
  prod_gas: [powerProductionBreakdown, gas, 0]
  prod_oil: [powerProductionBreakdown, oil, 0]
  prod_unknown: [powerProductionBreakdown, unknown, 0]
  prod_hydro_discharge: [powerProductionBreakdown, hydro discharge, 0]
  prod_battery_discharge: [powerProductionBreakdown, battery discharge, 0]

columns_to_select:
  - zone
  - date_time
  - updated_at
  - created_at
  - power_consumption_total
  - power_production_total
  - power_import_total
  - power_export_total
  - fossil_free_percentage
  - renewable_percentage
  - is_estimated
  - estimation_method
  - temporal_granularity
  - cons_nuclear
  - cons_geothermal
  - cons_biomass
  - cons_coal
  - cons_wind
  - cons_solar
  - cons_hydro
  - cons_gas
  - cons_oil
  - cons_unknown
  - cons_hydro_discharge
  - cons_battery_discharge
  - prod_nuclear
  - prod_geothermal
  - prod_biomass
  - prod_coal
  - prod_wind
  - prod_solar
  - prod_hydro
  - prod_gas
  - prod_oil
  - prod_unknown
  - prod_hydro_discharge
  - prod_battery_discharge