weather_extract_arg_map:
  extract_city: city
  extract_start_date: start_date
  extract_end_date: end_date

weather_clean_arg_map:
  clean_input_table: input_table
  clean_output_table: output_table
  clean_write_options: write_options
  clean_write_mode: write_mode